# works for ubuntu
- name: Install NGINX
  hosts: all
  become: yes #become block is needed when non root account is used to access remote VMs, this is typical for AWS
  become_user: root
  become_method: sudo
  vars:
      ansible_python_interpreter: /usr/bin/python3
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Wait for automatic system updates
    shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done; #Wait for lock to be released
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Install NGINX
    apt:
      name: nginx
      state: present
